name: Cavrnus Windows Direct Project Build
on: 
  push:
    branches: "dev/chn/lcl-runner"
jobs:
  windows_direct_runner_build:
    runs-on: self-hosted
    steps:
      - name: Config Git for Long Paths
        run: git config --global core.longpaths true
      - name: Cache Project
        id: project_cache
        uses: actions/cache@v3  # Caches the Cavrnus Connector plugin resources
        with:
          path: project/Plugins/CavrnusConnector
          key: "Plugin_Cache"
      - name: Checkout Project
        uses: actions/checkout@v4
        with:
          lfs: true
          path: project       # the path where the project will be extracted. Package and PluginPackage will be stored in the same dir level as the project dir
      - name: Build Project
        run: |
          cd project
          ./AutoBuild.bat ${{ vars.PROJ_NAME }} ${{ vars.UNREAL_PATH }}
      - name: Build Plugin
        run: |
          cd project
          ./PackagePlugin.bat ${{ vars.PLUGIN_NAME }} ${{ vars.UNREAL_PATH }}
      - name: Set Package to Upload
        uses: actions/upload-artifact@v3
        with:
          name: ${{ vars.PROJ_NAME }}_pkg
          path: Package/${{ vars.PROJ_NAME }}
      - name: Set Plugin to Upload
        uses: actions/upload-artifact@v3
        with:
          name: ${{ vars.PLUGIN_NAME }}_pkg
          path: PackagePlugin/${{ vars.PLUGIN_NAME }}
        
          


          
